#!/bin/bash

function parethesisCounter()
{
	input="$1";
	openCounter=0;
	closeCounter=0;
	
	for data in $(seq 1 ${#input});
	do
		if [[ $data = '(' ]]; then
			++openCounter;
		elif [[ $data = ')' ]]; then
			++closeCounter;
		fi;
	done;
	
	if [[ "$closeCounter" -eq "$openCounter" ]]; then
		result=$closeCounter;	
	elif [[ "$closeCounter" -gt "$openCounter" ]]; then
		result=$closeCounter;
	elif [[ "$closeCounter" -lt "$openCounter" ]]; then
		result=$openCounter;
	fi;
	
	return result;
}

parenthesisCounter '(())';
